### PR TITLE
[ADD] project_timesheet_activity_begin_end: Added widget on Begin and…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
… End hours.

### CODE REVIEW

**Review by nils-vertel — APPROVED** [review]

**Comment by fredrikarvas-vertel** [comment]
@rupareliyahemangi145 

I tested this and got: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedFunction: operator does not exist: integer = boolean
LINE 1: SELECT number_next FROM ir_sequence WHERE id=false FOR UPDAT...
                                                    ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

@nils-vertel sais he thinks we do a comparison between an integer and a bool.

Could you check please?

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

is this full error message?

**Comment by fredrikarvas-vertel** [comment]
Fel:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 240, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_timesheet/__init__.py", line 34, in create_internal_project
    project_ids = env['project.project'].create(project_vals)
  File "<decorator-gen-293>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_timesheet/models/project.py", line 69, in create
    return super(Project, self).create(vals_list)
  File "<decorator-gen-251>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/odoo-record-keeping/record_keeping_project/models/project.py", line 45, in create
    project = super(Project, self).create(vals)
  File "<decorator-gen-248>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/usr/share/odooext-OCA-project/project_key/models/project_project.py", line 38, in create
    new_project = super(Project, self).create(vals)
  File "<decorator-gen-222>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/project/models/project.py", line 352, in create
    project = super(Project, self).create(vals)
  File "<decorator-gen-123>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_alias_mixin.py", line 42, in create
    records = super(AliasMixin, self).create(valid_vals_list)
  File "<decorator-gen-129>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3870, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4028, in _create
    field.create([
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3041, in create
    self.write_batch(record_values, True)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3067, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3243, in write_real
    flush()
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3205, in flush
    comodel.create(to_create)
  File "<decorator-gen-252>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/odoo-record-keeping/record_keeping_project/models/task.py", line 45, in create
    task = super(Task, self).create(vals)
  File "<decorator-gen-250>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/usr/share/odooext-OCA-project/project_task_code/models/project_task.py", line 26, in create
    return super().create(vals_list)
  File "<decorator-gen-249>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/odooext-OCA-project/project_key/models/project_task.py", line 37, in create
    vals["key"] = project.get_next_task_key()
  File "/usr/share/odooext-OCA-project/project_key/models/project_project.py", line 125, in get_next_task_key
    return self.sudo().task_key_sequence_id.next_by_id()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 271, in next_by_id
    return self._next(sequence_date=sequence_date)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 260, in _next
    return self._next_do()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 201, in _next_do
    number_next = _update_nogap(self, self.number_increment)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_sequence.py", line 56, in _update_nogap
    self._cr.execute("SELECT number_next FROM %s WHERE id=%%s FOR UPDATE NOWAIT" % self._table, [self.id])
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedFunction: operator does not exist: integer = boolean
LINE 1: SELECT number_next FROM ir_sequence WHERE id=false FOR UPDAT...
                                                    ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

**Comment by fredrikarvas-vertel** [comment]
This is the full error message. 
Maybe @nils-vertel  can add more info.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

This error is comes from following module:
File "/usr/share/odooext-OCA-project/project_key/models/project_project.py", line 125, in get_next_task_key
return self.sudo().task_key_sequence_id.next_by_id()

**Comment by fredrikarvas-vertel** [comment]
Thanks Hemangi.
I will uninstall that module.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

If you want to fix this error then please provide me info that this error is on Dev-12.0 or on Fenix. So I can test on that db.

**Comment by fredrikarvas-vertel** [comment]
It now sais: 
the demoe-data faild to installe
<html>
<body>


while parsing /usr/lib/python3/dist-packages/odoo/addons/sale_timesheet/data/sale_service_demo.xml:167, near <function model="project.task" name="write"> <value model="project.task" eval="obj().search([('sale_line_id', '=', ref('sale_line_13'))]).ids"/> <value eval="{'user_id': ref('base.user_admin')}"/> </function>
--



</body>
</html>

**Comment by rupareliyahemangi145** [comment]
Can we connect and check together?

**Pull request merged**
